version: '2'
services:
  web:
    build: .
    command: [npm, start]
    environment:
      - PORT=8000
    labels:
      - convox.health.path=/status
      - convox.health.port=8000
    ports:
      - 80:8000
